<?php
if (PHP_SAPI !== 'cli') exit(1);
$_SERVER['HTTP_HOST'] = 'fixture.example.invalid';
$_SERVER['HTTPS'] = 'on';
$wordpress = $argv[1] ?? '';
if (!preg_match('#^/tmp/nc-woo-runtime\\.[A-Za-z0-9]+$#D', $wordpress) || !is_file($wordpress . '/wp-load.php')) exit(2);
require $wordpress . '/wp-load.php';
if (DB_NAME !== 'nc_woo_runtime_fixture' || !DISABLE_WP_CRON || !WP_HTTP_BLOCK_EXTERNAL) exit(2);
$storage = $argv[2] ?? 'posts';
if (!in_array($storage, ['posts', 'hpos'], true)) exit(2);
$isHpos = \Automattic\WooCommerce\Utilities\OrderUtil::custom_orders_table_usage_is_enabled();
if ($isHpos !== ($storage === 'hpos')) throw new RuntimeException('Requested order storage is not active');
require_once __DIR__ . '/../neurocheckout-connector.php';
NCWooConnector::instance()->activate();
global $wpdb;
$wpdb->query('DELETE FROM wp_woocommerce_sessions'); // Disposable fixture only.
update_option('woocommerce_currency', 'USD');
update_option('woocommerce_prices_include_tax', 'no');
WC()->initialize_session();
WC()->initialize_cart();
WC()->customer->set_billing_email('synthetic@example.invalid');
WC()->customer->set_billing_first_name('Synthetic');
WC()->customer->save();
$product = new WC_Product_Simple();
$product->set_name('Synthetic source product');
$product->set_status('publish');
$product->set_regular_price('12.50');
$product->set_virtual(true);
$product->save();
$key = WC()->cart->add_to_cart($product->get_id(), 2);
if (!$key) throw new RuntimeException('Native add to cart failed');
WC()->cart->calculate_totals();
$session = new WC_Cart_Session(WC()->cart);
$session->set_session();
$runtimeCart = 'synthetic-runtime-cart-' . bin2hex(random_bytes(8));
WC()->session->set('ncwoo_runtime_cart_id', $runtimeCart);
WC()->session->save_data();
$config = new NCWooConfig();
update_option(NCWooConfig::OPTION_API_ENDPOINT, 'https://community-api-staging.neurocheckout.com');
update_option(NCWooConfig::OPTION_API_KEY, 'fixture-api-key');
update_option(NCWooConfig::OPTION_SHOP_EXTERNAL_ID, 'fixture-shop');
update_option(NCWooConfig::OPTION_API_TEST_VALIDATED_AT, time());
update_option(NCWooConfig::OPTION_API_TEST_VALIDATION_FINGERPRINT, hash('sha256', 'https://community-api-staging.neurocheckout.com|fixture-api-key|fixture-shop'));
$binding = ['nativeScope'=>1, 'platform'=>'woocommerce', 'environment'=>'staging', 'enabled'=>true,
    'shopId'=>'fixture-shop', 'secret'=>NeuroCheckout\WooCommerce\Community\AutomaticSourceBinding::secret('fixture-api-key', 'fixture-shop')];
$reader = NeuroCheckout\WooCommerce\Community\WooSourceSnapshotFactory::create(1, $binding);
$snapshot = $reader->capture(1);
$carts = array_values(array_filter($snapshot, static function ($row) { return $row['kind']==='cart' && $row['payload']['status']==='active'; }));
if (!$carts) throw new RuntimeException('Native session not exported');
$latest = end($carts)['payload'];
if ((string)($latest['stored_totals']->total ?? '') !== '25.00' && (float)($latest['stored_totals']->total ?? -1) !== 25.0) throw new RuntimeException('Native total mismatch');
if (($latest['customer']->email ?? $latest['customer']->billing_email ?? '') !== 'synthetic@example.invalid') throw new RuntimeException('Native contact missing');
$path = '/wp-json/neurocheckout/v1/communitydata';
$_SERVER['REQUEST_URI'] = $path;
$body = json_encode(['schema'=>1, 'shopId'=>'fixture-shop', 'streamId'=>null, 'cursor'=>'', 'limit'=>8]);
$nonce = bin2hex(random_bytes(16)); $time = (string)(int)floor(microtime(true)*1000);
$_SERVER['CONTENT_TYPE'] = 'application/json';
$_SERVER['HTTP_X_NC_SOURCE_TIME'] = $time;
$_SERVER['HTTP_X_NC_SOURCE_NONCE'] = $nonce;
$_SERVER['HTTP_X_NC_SOURCE_SIGNATURE'] = hash_hmac('sha256', implode("\n", ['nc-source-pull-v1','POST',$path,'fixture-shop',$time,$nonce,hash('sha256',$body)]), hex2bin($binding['secret']));
$request = new WP_REST_Request('POST', '/neurocheckout/v1/communitydata');
$request->set_body($body);
$response = NCWooCommunitySource::pull($request);
if ($response->get_status() !== 200) throw new RuntimeException('Signed native route failed: '.$response->get_data());
$signature = $response->get_headers()['X-NC-Source-Response'] ?? '';
$expected = NeuroCheckout\WooCommerce\Community\SourcePullProtocol::responseSignature($binding['secret'], $nonce, $response->get_data());
if (!hash_equals($expected, $signature)) throw new RuntimeException('Response signature mismatch');
if (NCWooCommunitySource::pull($request)->get_status() !== 409) throw new RuntimeException('Replay was accepted');
$projection = new NeuroCheckout\WooCommerce\Community\WooSessionProjection($binding['secret'], 1, 'fixture-shop');
$cartReference = $projection->cartReference($runtimeCart);
$order = wc_create_order();
$order->set_billing_email('synthetic@example.invalid');
$order->add_product($product, 2);
do_action('woocommerce_checkout_create_order', $order, []);
$order->calculate_totals();
$order->save();
if ($order->get_meta('_ncwoo_cart_id') !== $runtimeCart) throw new RuntimeException('Classic checkout link missing');
$snapshot = $reader->capture(1);
$linked = array_values(array_filter($snapshot, static function ($row) use ($cartReference) { return $row['sourceId'] === $cartReference; }));
if (count($linked)!==1 || $linked[0]['payload']['status']!=='order_present') throw new RuntimeException('Order failed to suppress active cart');
if ($linked[0]['payload']['conversion_status']!=='linked_order_not_payment_proof') throw new RuntimeException('Pending order falsely treated as paid');
WC()->session->destroy_session();
$snapshot = $reader->capture(1);
$linked = array_values(array_filter($snapshot, static function ($row) use ($cartReference) { return $row['sourceId'] === $cartReference; }));
if (count($linked)!==1 || $linked[0]['payload']['session_status']!=='absent') throw new RuntimeException('Order lost after session removal');
// Exercise the separately registered Checkout Block hook with native WC CRUD.
// This is not a browser payment or an end-to-end Store API checkout.
$blockCart = 'synthetic-block-cart-' . bin2hex(random_bytes(8));
WC()->session->set('ncwoo_runtime_cart_id', $blockCart);
$blockOrder = wc_create_order();
$blockOrder->set_billing_email('synthetic@example.invalid');
$blockOrder->add_product($product, 1);
$blockOrder->calculate_totals();
$blockOrder->save();
do_action('woocommerce_store_api_checkout_order_processed', $blockOrder);
$reloadedBlock = wc_get_order($blockOrder->get_id());
if ($reloadedBlock->get_meta('_ncwoo_cart_id') !== $blockCart) throw new RuntimeException('Checkout Block cart link not persisted');
$blockReference = $projection->cartReference($blockCart);
$blockRows = array_values(array_filter($reader->capture(1), static function ($row) use ($blockReference) { return $row['sourceId'] === $blockReference; }));
if (count($blockRows)!==1 || $blockRows[0]['payload']['status'] !== 'order_present') throw new RuntimeException('Checkout Block order not exported');
$customStore = static function ($stores) { return $stores; };
add_filter('woocommerce_data_stores', $customStore);
$rejected = false;
try { NeuroCheckout\WooCommerce\Community\WooSourceSnapshotFactory::create(1, $binding); }
catch (RuntimeException $error) { $rejected = $error->getMessage() === 'source_schema_unavailable'; }
remove_filter('woocommerce_data_stores', $customStore);
if (!$rejected) throw new RuntimeException('Unknown storage override accepted');
echo 'PASS: real WordPress '.get_bloginfo('version').' / WooCommerce '.WC_VERSION.' bootstrap, native guest session, totals, automatic binding, signed route and replay rejection.' . PHP_EOL;
echo "PASS: {$storage} order storage, classic and Checkout Block hook links, pending-order suppression, session removal, custom storage refusal.\n";
